### ISSUE TITLE
Duplicate db.init_app(app) in seed.py

### ISSUE THREAD

**Issue by samchappel** [learn-co-curriculum/python-p4-flask-restful-cr#4]
### Canvas Link

https://learning.flatironschool.com/courses/6259/assignments/233453?module_item_id=547405

### Concern

There is a duplicate ```db.init_app(app)``` in the seed.py file - you aren't able to seed the database until it is removed or commented out.

**Comment by professor-ben** [comment]
Hi Sam,

Thanks for the report! This was a sneaky issue that we've been clearing up in every repo- if you catch it anywhere else, please let us know!

Thanks again,
Ben
